name: fetch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  fetch-dependencies:
    strategy:
      matrix:
        script-name: [fetch-robolectric-dependencies.sh, fetch-robolectric-preinstrumented-dependencies.sh]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.script-name }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ matrix.script-name }}

      - name: Fetch dependencies
        run: source ${{ matrix.script-name }}

